# Generated by Django 3.1.4 on 2021-06-17 23:59

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OGS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(blank=True, max_length=100, null=True)),
                ('graduate_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('program', models.CharField(blank=True, max_length=100, null=True)),
                ('research_discipline', models.CharField(blank=True, max_length=100, null=True)),
                ('level_of_study', models.CharField(blank=True, max_length=50, null=True)),
                ('year_of_study', models.IntegerField(blank=True, null=True)),
                ('award_start_session', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_completion_degree_requirements', models.DateField(blank=True, null=True)),
                ('student_number', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('address_city', models.CharField(blank=True, max_length=100, null=True)),
                ('address_province', models.CharField(blank=True, max_length=100, null=True)),
                ('address_country', models.CharField(blank=True, max_length=100, null=True)),
                ('citizenship_status', models.CharField(blank=True, max_length=50, null=True)),
                ('self_identify_indigenous', models.BooleanField(blank=True, null=True)),
                ('self_identify_black', models.BooleanField(blank=True, null=True)),
                ('current_loan', models.BooleanField(blank=True, null=True)),
                ('vanier', models.IntegerField(blank=True, null=True)),
                ('sshrc', models.IntegerField(blank=True, null=True)),
                ('nserc', models.IntegerField(blank=True, null=True)),
                ('cihr', models.IntegerField(blank=True, null=True)),
                ('ogs', models.IntegerField(blank=True, null=True)),
                ('que2', models.IntegerField(blank=True, null=True)),
                ('ots', models.IntegerField(blank=True, null=True)),
                ('consider_other', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Activation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_number', models.IntegerField(blank=True, null=True)),
                ('faculty', models.CharField(blank=True, max_length=200, null=True)),
                ('graduate_unit', models.CharField(blank=True, max_length=200, null=True)),
                ('program', models.CharField(blank=True, max_length=200, null=True)),
                ('degree_start_date', models.DateField(blank=True, null=True)),
                ('award', models.CharField(blank=True, max_length=200, null=True)),
                ('award_duration', models.CharField(blank=True, max_length=200, null=True)),
                ('type_payment_request', models.CharField(blank=True, max_length=200, null=True)),
                ('award_start_session', models.CharField(blank=True, max_length=200, null=True)),
                ('submitted', models.BooleanField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('confirmation_number', models.CharField(default=api.models.generate_confirmation_number, max_length=25, unique=True)),
                ('admin_research_requirement', models.CharField(blank=True, max_length=200, null=True)),
                ('admin_matching_portion', models.CharField(blank=True, max_length=500, null=True)),
                ('admin_utf', models.IntegerField(blank=True, null=True)),
                ('admin_departmental_award', models.IntegerField(blank=True, null=True)),
                ('admin_ta', models.IntegerField(blank=True, null=True)),
                ('admin_ra', models.IntegerField(blank=True, null=True)),
                ('admin_other_source', models.IntegerField(blank=True, null=True)),
                ('admin_payment_notes', models.CharField(blank=True, max_length=500, null=True)),
                ('admin_submitted', models.BooleanField(blank=True, null=True)),
                ('admin_submitted_at', models.DateTimeField(blank=True, default='', null=True)),
                ('admin_confirmation_number', models.CharField(default=api.models.admin_generate_confirmation_number, max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
