# Generated by Django 3.1.4 on 2023-03-19 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
    ]
