# Generated by Django 3.1.4 on 2023-03-23 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='confirmation_number',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='api.payment_activation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(default='janedoe', on_delete=django.db.models.deletion.CASCADE, related_name='document', to='users.customuser', to_field='username'),
            preserve_default=False,
        ),

    ]
