# Generated by Django 3.1.4 on 2023-03-24 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230323_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='confirmation_number',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.AddField(
            model_name='document',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='api.payment_activation'),
            preserve_default=False,
        ),
    ]
