# Generated by Django 3.1.4 on 2021-06-05 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210604_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_activation',
            name='submitted_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 5, 11, 23, 50, 400455), null=True),
        ),
    ]
