# Generated by Django 3.1.4 on 2021-06-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210605_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_activation',
            name='submitted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
