# Generated by Django 3.1.4 on 2023-06-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230405_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_activation',
            name='admin_award_letter_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
