# Generated by Django 3.1.4 on 2021-06-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210605_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_activation',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='payment_activation',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
