# Generated by Django 3.1.4 on 2021-06-07 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_auto_20210605_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_activation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_activation', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
