# Generated by Django 3.1.4 on 2021-06-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210606_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_activation',
            name='award',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment_activation',
            name='award_duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment_activation',
            name='award_start_session',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment_activation',
            name='faculty',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment_activation',
            name='graduate_unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment_activation',
            name='program',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment_activation',
            name='type_payment_request',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
