# Generated by Django 3.2.20 on 2023-08-09 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_payment_activation_award_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_activation',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_payment_activation', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='payment_activation',
            name='award_letter',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
