# Generated by Django 3.1.4 on 2021-06-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210615_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_activation',
            name='student_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
