name: 🚀 Deploy Forms

on: 
  push:
    branches:    
      - main

jobs:
  frontend-deploy:
    name: 🎉 Deploy Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react_forms
    
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}

    - name: 🔨 Build Project 
      run: |
        npm install
        npm run build
    
    - name: List output files
      run: find build/ -print

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_FE_SERVER }}
        username: ${{ secrets.FTP_FE_USERNAME }}
        password: ${{ secrets.FTP_FE_PASSWORD }}
        local-dir: react_forms/build/

  backend-test:
    name: 🎉 Django Tests CI

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: django_forms
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
      
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DJANGO_SECRET_KEY : ${{ secrets.DJANGO_SECRET_KEY}}
        DJANGO_OPENAI_API_KEY : ${{ secrets.DJANGO_OPENAI_API_KEY}}
        ALLOWED_HOSTS : ${{ secrets.ALLOWED_HOSTS}}
        AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        DEVELOPMENT_AWS_STORAGE_BUCKET_NAME : ${{ secrets.DEVELOPMENT_AWS_STORAGE_BUCKET_NAME}}
        PRODUCTION_AWS_STORAGE_BUCKET_NAME : ${{ secrets.PRODUCTION_AWS_STORAGE_BUCKET_NAME}}
        AWS_S3_REGION_NAME : ${{ secrets.AWS_S3_REGION_NAME}}
        
        # include all other env variables here
      run: |
        python manage.py test

  backend-deploy:
    name: 🎉 Deploy Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: django_forms
    
    strategy:
      matrix:
        node-version: [16.x]
        # python version?
    
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

      # transfers are already static and can be simply copied over
    
    - name: List django project files
      run: find django_forms// -print

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_BE_SERVER }}
        username: ${{ secrets.FTP_BE_USERNAME }}
        password: ${{ secrets.FTP_BE_PASSWORD }}
        local-dir: django_forms/